### ISSUE TITLE
Recommemded i18n implementation to use with Jadeify?

### ISSUE THREAD

**Issue by antoniobrandao** [domenic/jadeify#24]
Hello,

I'm finding it hard to find a i18n solution to integrate with Jadeify, which I am using with Express / Browserify / Gulp.

Can anyone make a recommendation for this? And provide a simple example? I'd like to be able to add i18n directly into the jade templates to use in a single-page app.

Thanks!

**Comment by domenic** [comment]
This isn't a bug in Jadeify. I'd suggest asking on StackOverflow.

**Comment by ForbesLindesay** [comment]
Also consider trying on the jade issue tracker itself as someone else may have a generic solution (not tied to jadeify)
