### ISSUE TITLE
Fatal error: Cannot set property 'filename' of undefined

### ISSUE THREAD

**Issue by jantimon** [domenic/jadeify#25]
jadefiy crashes if no options are passed: "Fatal error: Cannot set property 'filename' of undefined":

https://github.com/domenic/jadeify/blob/master/lib/jadeify.js#L19

**Comment by domenic** [comment]
Why are you calling jadeify directly? The correct usage shown in the readme is

```js
bundle.transform(require("jadeify"));
```

**Comment by jantimon** [comment]
Who said that?

I am using grunt-watchify (0.1.0) which uses browserify (2.36.1).
The grunt task is configured as follows:

```js
     watchify: {
        options: {
          // defaults options used in b.bundle(opts)
          detectGlobals: false,
          insertGlobals: false,
          ignoreMissing: false,
          debug: false,
          standalone: false,
          keepalive: false,
          callback: function(b) {
            b.transform(require('jadeify'), {pretty: false});
            return b;
          }
        }
```

Then in my index.js I am trying to load test.jade:

```js
var template = require('./demo/test.jade');
```

**Comment by jantimon** [comment]
Other modules e.g. sassify handles empty options like this:

```js
options = extend({}, globalOptions || {});
```

https://github.com/davidguttman/sassify/blob/master/lib/index.js#L15

**Comment by domenic** [comment]
You implied that, in the OP, by saying that you were "calling" it instead of passing it to browserify.transform.

Anyway, the issue here is that your browserify is 6 major versions of out date. I will try to debug the latest working version and update this package's peer dependencies to require it.
