### ISSUE TITLE
Using jadeify as a dependency

### ISSUE THREAD

**Issue by Industrial** [domenic/jadeify#31]
Hi.

Instead of writing a gulp file for each of my project, I've created a NPM module that I require instead; https://github.com/Industrial/id-builder

I would like to add the jadeify transform here https://github.com/Industrial/id-builder/blob/issues/27/src/lib/browserify.js#L55 .

The problem I'm having is that when I use id-builder in another project, it will not find jade and error. It seems to take the jade/runtime module from the project that's invoking jadeify, not the project that's requiring it.

Is there a way to solve this without adding jade as a dependency whenever I add id-builder as a dependency?

**Comment by domenic** [comment]
This is an interesting problem, hmm.

You could try making jade a peer dependency of id-builder, but I'm not sure that's the best solution...

I would accept a PR that adds a `runtimePath` option, which defaults to `"jade/runtime"` but can be overriden. Then inside your module you could pass in e.g. `runtimePath: require.resolve("jade/runtime")`.

**Comment by Industrial** [comment]
Done :-) https://github.com/domenic/jadeify/pull/32
