### ISSUE TITLE
Not compile to index.html

### ISSUE THREAD

**Issue by pokaxperia** [domenic/jadeify#34]
Hello, I have two scripts.js where each one have two "require templates"
![screen shot 2015-06-22 at 22 08 27](https://cloud.githubusercontent.com/assets/1803166/8298186/41c89828-192b-11e5-835b-b408e009e4cd.png)

login.js
![screen shot 2015-06-22 at 22 05 07](https://cloud.githubusercontent.com/assets/1803166/8298167/cd09fb30-192a-11e5-96ce-0803c413df86.png)

layout.js
![screen shot 2015-06-22 at 22 05 13](https://cloud.githubusercontent.com/assets/1803166/8298171/d2ea6e2c-192a-11e5-8b00-8f69857e6342.png)

and I use this command line:
"build": "browserify -t babelify -t jadeify lib/app.js > public/app.js"

but not compile from index.jade to index.html, in fact, after run this command, index.html don't appear and no error appear. I'm use page.js for routes.

Can you help me?, because I don't find the error

**Comment by domenic** [comment]
This question doesn't really appear to be related to jadeify. I'd suggest asking it on StackOverflow.
