### ISSUE TITLE
Peer dependencies error with Browserify v11

### ISSUE THREAD

**Issue by Aldream** [domenic/jadeify#36]
Calling `npm install jadeify`:

    npm ERR! peerinvalid The package browserify does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer jadeify@4.3.0 wants browserify@>= 2.4.0 < 11

The problem is covered by pending PR #35.

**Comment by domenic** [comment]
Fixed by b7a30a33111efeb5295949747e312dce3fb800fe and will be released in 4.4.0.
