### ISSUE TITLE
Allow ignore config

### ISSUE THREAD

**Issue by acoll** [domenic/jadeify#41]
I'm looking to ignore a pattern of files (basically node_modules). The use case is a module that has a jadeify already specified in its package.json. When its two levels deep jadeify tries to jadeify the already compiled js. Maybe i'm missing something and there is a better way to apply transforms only to some files.

I can fork and work on it and then send a pull request but I want to get an idea of whether this is the right path to go down or not.

**Comment by acoll** [comment]
This wont work anyways. I tend to symlink some projects under node_modules while developing, and the requires get an absolute path to the file anyways. Closing.

**Comment by domenic** [comment]
Transforms should not be applying to your dependencies unless you use the --global-transform browserify flag:

> ```
>   --transform, -t  Use a transform module on top-level files.
> ```

https://github.com/substack/node-browserify#usage

**Comment by acoll** [comment]
Good point. I'm using the grunt-browserify plugin so I'll have to look at
that source to see whats going on. I've had a similar issue with another
transform screwing up one of my dependencies too.

Thanks for the feedback.
